# Generated by Django 5.2.3 on 2025-07-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='exampleemail@example.com', max_length=100),
        ),
    ]
