# Generated by Django 5.2.3 on 2025-07-07 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_category_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='expense_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
