# Generated by Django 5.2.3 on 2025-07-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_expenses_description_expenses_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user_id',
        ),
    ]
