# Generated by Django 5.2.3 on 2025-07-14 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_category_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='year',
        ),
        migrations.AddField(
            model_name='budget',
            name='month_year',
            field=models.DateField(default=datetime.date(2025, 7, 1)),
            preserve_default=False,
        ),
    ]
