# Generated by Django 5.2.3 on 2025-07-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_remove_budget_month_remove_budget_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='month_year',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(choices=[(2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=7),
        ),
    ]
